/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ismartv_util_JniSetting */

#ifndef _Included_com_ismartv_util_JniSetting
#define _Included_com_ismartv_util_JniSetting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ismartv_util_JniSetting
 * Method:    setDisplayMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ismartv_util_JniSetting_setDisplayMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ismartv_util_JniSetting
 * Method:    getDisplayMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ismartv_util_JniSetting_getDisplayMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
