/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class novel_supertv_dvb_jni_JniSetting_GetWorkTime */

#ifndef _Included_novel_supertv_dvb_jni_JniSetting_GetWorkTime
#define _Included_novel_supertv_dvb_jni_JniSetting_GetWorkTime
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
